# Generated by Django 3.0.2 on 2020-01-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontects',
            name='attachment_file',
            field=models.FileField(blank=True, upload_to='assets/uploads/website'),
        ),
        migrations.AlterField(
            model_name='websitecontects',
            name='attachment_image',
            field=models.ImageField(blank=True, upload_to='assets/img/website'),
        ),
        migrations.AlterField(
            model_name='websitecontects',
            name='datafeatured',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='websitecontects',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='websitecontects',
            name='heading1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='websitecontects',
            name='heading2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='websitecontects',
            name='websection',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
