# Generated by Django 3.0.2 on 2020-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200120_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontects',
            name='attachment_file',
            field=models.FileField(blank=True, upload_to='website/uploads'),
        ),
        migrations.AlterField(
            model_name='websitecontects',
            name='attachment_image',
            field=models.ImageField(blank=True, upload_to='website/images'),
        ),
    ]
