# Generated by Django 3.0.2 on 2020-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='destination_image',
            field=models.ImageField(upload_to='destinatiions'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='region_featured_image',
            field=models.ImageField(upload_to='regions'),
        ),
    ]
